# GISAID Related (last updated 2023/06/26)
GISAID_TYPE = 'betacoronavirus'
GISAID_FIELDS = [
    'submitter',
    'fn',
    'covv_virus_name',
    'covv_type',
    'covv_passage',
    'covv_collection_date',
    'covv_location',
    'covv_add_location',
    'covv_host',
    'covv_add_host_info',
    'covv_sampling_strategy',
    'covv_gender',
    'covv_patient_age',
    'covv_patient_status',
    'covv_specimen',
    'covv_outbreak',
    'covv_last_vaccinated',
    'covv_treatment',
    'covv_seq_technology',
    'covv_assembly_method',
    'covv_coverage',
    'covv_orig_lab',
    'covv_orig_lab_addr',
    'covv_provider_sample_id',
    'covv_subm_lab',
    'covv_subm_lab_addr',
    'covv_subm_sample_id',
    'covv_consortium',
    'covv_authors',
    'covv_comment',
    'comment_type'
]

GISAID_HEADERS = {
    'submitter': 'Submitter',
    'fn': 'FASTA filename',
    'covv_virus_name': 'Virus name',
    'covv_type': 'Type',
    'covv_passage': 'Passage details/history',
    'covv_collection_date': 'Collection date',
    'covv_location': 'Location',
    'covv_add_location': 'Additional location information',
    'covv_host': 'Host',
    'covv_add_host_info': 'Additional host information',
    'covv_sampling_strategy': 'Sampling Strategy',
    'covv_gender': 'Gender',
    'covv_patient_age': 'Patient age',
    'covv_patient_status': 'Patient status',
    'covv_specimen': 'Specimen source',
    'covv_outbreak': 'Outbreak',
    'covv_last_vaccinated': 'Last vaccinated',
    'covv_treatment': 'Treatment',
    'covv_seq_technology': 'Sequencing technology',
    'covv_assembly_method': 'Assembly method',
    'covv_coverage': 'Coverage',
    'covv_orig_lab': 'Originating lab',
    'covv_orig_lab_addr': 'Address',
    'covv_provider_sample_id': 'Sample ID given by the sample provider',
    'covv_subm_lab': 'Submitting lab',
    'covv_subm_lab_addr': 'Address',
    'covv_subm_sample_id': 'Sample ID given by the submitting laboratory',
    'covv_consortium': 'Sequencing consortium',
    'covv_authors': 'Authors',
    'covv_comment': 'Comment',
    'comment_type': 'Comment Icon'
}
